name: CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Docker Image
        run: |
          docker build -t cockroachdb-remote-client:test .
          docker run --rm -d --name test-container \
            -e COCKROACH_HOST=localhost:26257 \
            -e COCKROACH_INSECURE=true \
            -e DATABASE_NAME=test \
            cockroachdb-remote-client:test
          sleep 5
          docker logs test-container
          docker stop test-container || true

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cockroachdb-remote-client:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'