name: CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Docker Image
        run: |
          docker build -t cockroachdb-remote-client:test .
          # Run container and capture exit code (it's expected to exit after completing tasks)
          docker run --name test-container \
            -e COCKROACH_HOST=localhost:26257 \
            -e COCKROACH_INSECURE=true \
            -e DATABASE_NAME=test \
            cockroachdb-remote-client:test || EXIT_CODE=$?
          
          # Check logs to verify it ran
          docker logs test-container
          
          # Clean up container
          docker rm test-container || true
          
          # The container should exit with code 0 or a connection error (expected without a real CockroachDB)
          if [ ! -z "$EXIT_CODE" ] && [ "$EXIT_CODE" != "0" ] && [ "$EXIT_CODE" != "1" ]; then
            echo "Container exited with unexpected code: $EXIT_CODE"
            exit 1
          fi

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cockroachdb-remote-client:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'