# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Validate Maven wrapper
      run: |
        if [ -f "mvnw" ]; then
          chmod +x mvnw
          ./mvnw --version
        else
          mvn --version
        fi

    - name: Compile with Maven
      run: |
        if [ -f "mvnw" ]; then
          ./mvnw -B compile --file pom.xml
        else
          mvn -B compile --file pom.xml
        fi

    - name: Package with Maven
      run: |
        if [ -f "mvnw" ]; then
          ./mvnw -B package --file pom.xml
        else
          mvn -B package --file pom.xml
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: jar-artifacts
        path: target/*.jar
        retention-days: 30
